### ISSUE TITLE
Install on Raspberry Pi OS?

### ISSUE THREAD

**Issue by grivanov** [stsaz/phiola#17]
I'm quite new to SBC and RaspberryPi but I used fmedia for a few years now. I see you provide arm64 version but only as .APK file for Android. Is it possible to get a Linux arm64 version?

**Comment by stsaz** [comment]
Hi!
Yes, I can add cross-compiled version for Linux/arm64.
Which glibc version is currently installed on your RaspberryPi?
It should be something like `glibc-2.xx` (look for it in the list of installed packages on your OS).

**Comment by grivanov** [comment]
Hi, it seems to be: (Debian GLIBC 2.36-9+rpt2+deb12u4) 2.36
That's what you needed, right? Thank you very much for helping out :)

**Comment by stsaz** [comment]
Done.

https://github.com/stsaz/phiola/releases

the file name is `phiola-2.0-rc20-linux-arm64.tar.zst`
