### ISSUE TITLE
[FAEATURE REQUEST] Batch Convert

### ISSUE THREAD

**Issue by 0xlne** [stsaz/phiola#18]
As a user who regularly converts audio files between formats, it would be very useful for phiola to be able to batch select/convert files.

**Comment by stsaz** [comment]
Done!
Available for testing: https://github.com/stsaz/phiola/releases/tag/v2.1-beta1

Note: background service for a long conversion process isn't yet implemented (and I didn't even test this case), so just *don't let your Android go to sleep* (i.e. screen off) while phiola is still converting.

**Comment by stsaz** [comment]
I consider this feature complete in v2.1-rc4.  Although there are still some minor issues, but they can be addressed later.

**Comment by 0xlne** [comment]
I have tested this feature on ~100 flac files & phiola deals with the conversions consistently. Thank you for implementing this feature.
