### ISSUE TITLE
Audio player doesn't sync with system controls for Android

### ISSUE THREAD

**Issue by CoolCrescent186** [stsaz/phiola#19]
For Android 13+ (at least, I don't have any Android devices less than 13), when clicking the play button from the notification audio controller, Phiola will start playing the audio, but will not sync the time elapsed. Say I played a track, and paused it (through Phiola). No problem. When I start it via Phiola, no problem. When I pause it through the system control, it can take an unexpected click or two, but it does pause. When I click play, it takes a lot of clicks, but does eventually play. This is where the problem begins. The audio will play, but Phiola disagrees with that. If I pause the audio, it does stop playing. If I open Phiola, the playback slider (and time elapsed/remaining) have not changed. This becomes more of a problem when the end of the track is reached, because Phiola will not move on to the next one without intervention (not ideal for listening to tunes while driving). This doesn't feel intentional, but if it is, please let me know.

**Comment by stsaz** [comment]
Hi!  
I tried to reproduce the issue on Android 11 but I couldn't do it - everything works as expected for me.  I will try to reproduce this on Android 13.  

> When I click play, it takes a lot of clicks, but does eventually play. ... The audio will play, but Phiola disagrees with that.

Do you mean that when you open phiola, while the audio is playing, phiola doesn't display `[Playing]` status in the title?  
And does this happen only after **several** clicks on Play button from the notification controller?
And when you press Play button from the notification controller **just once** - phiola still doesn't display `[Playing]` status even after you wait for several seconds?

BTW, do you have some kind of battery saving service active on you Android that can maybe get in the way somehow?

**Comment by CoolCrescent186** [comment]
No battery saving service, but I must be going crazy or something. The only bug now is that if you pause from Phiola, Android thinks you're still playing as far as notification audio player thing goes. Takes two clicks. I'll update this if it changes, but I guess it's not a problem. I'll update this to "solved" for now.
