### ISSUE TITLE
Backward compatibility of CLI switches with Fmedia

### ISSUE THREAD

**Issue by sergeevabc** [stsaz/phiola#21]
Windows 7 x64, Phiola 2.0rc19 (and Fmedia 1.31).

Dear @stsaz,
I am used to listening to multiple files on repeat as follows `fmedia 01.flac 02.flac 03.flac --repeat-all`. But not only you replaced `--` with `-` in Phiola, but also replaced `...-all` with `_all` which requires pressing Shift to type that underscore. It's painful. Please consider making the CLI switches backwards compatible, or at least similar to the previous ones, if possible.

**Comment by stsaz** [comment]
Hi!

> fmedia 01.flac 02.flac 03.flac --repeat-all

With phiola you can do this:

`phiola 01.flac 02.flac 03.flac -rep`

In other words, you don't need to type *all* characters for `-repeat_all` option, you may type just the prefix for it (enough for phiola to recognize it).

> Please consider making the CLI switches backwards compatible

It's very easy to add aliases to the switches, but this needs to have a very good reason for doing so.  Considering `-repeat_all` switch that you can type just as `-repeat` or `-rep` - it's much better than typing `--repeat-all`, IMO.
