### ISSUE TITLE
[Android] Opus recordings sounding like filtered

### ISSUE THREAD

**Issue by EthicalGhost** [stsaz/phiola#22]
Opus recordings are sounding more like filtered (noisy) rather than natural. I changed only these few things in the settings:
Channels: Mono
Bitrate: 32 kbps
Sample rate: 48000 hz

I compared its produced Opus sound with other recorders (recforge, record you), but Phiola's output is like filtered or thinned out. I tested other encoder (AAC-LC) sound and it's fine.

**Comment by stsaz** [comment]
Is this on Android?  Which CPU arch?  Does the problem persist if you record with default settings?  Most probably phiola's sample rate conversion is the reason (Opus requires 48khz rate, while AAC doesn't) - I will test this once again on my device.

**Comment by EthicalGhost** [comment]
> Is this on Android? Which CPU arch? Does the problem persist if you record with default settings? Most probably phiola's sample rate conversion is the reason (Opus requires 48khz rate, while AAC doesn't) - I will test this once again on my device.

1. Yes, on Android11. Device is a Samsung Galaxy.
2. It's ARM64 supported.
3. With default settings, the sound quality is natural. (It's only with OPUS that the sound output seems filtered. It's like when in cancelling or suppressing background noise, the audio quality gets thinned out or looses its original or natural sound quality.)

**Comment by stsaz** [comment]
> It's only with OPUS that the sound output seems filtered

I've just tested voice recording on my arm64 device, and Opus sounds the same as AAC-LC to me (both not great quality sound, to be honest).
My settings:
* Channels: Default
* Sample Rate: Default
* Encoder: Opus
* Bitrate: 32
* Buffer Length: 500
* Dynamic Audio Normalizer: Disabled
* Gain: 0
Please check once again - do you have the exactly same settings?

Also, the Opus encoder used for recording in phiola is the same code that is used for conversion.
So we can easily test it on your device if you select some good quality audio track (say, 320kbps mp3) and convert it to Opus 128kbps using phiola.
It will produce very good quality file, it sounds just like the original.
Now try to convert the same 320kbps mp3 file to Opus 32kbps, and immediately we can tell the difference - 32kbps is not enough for good quality sound.

What I mean is that you can try to set 128kbps Opus quality for your recording - does it sound fine then?

**Comment by EthicalGhost** [comment]
> Please check once again - do you have the exactly same settings?

I reinstalled the app and tried again, now it is okay. Maybe I have done something wrong in the settings earlier.

> both not great quality sound, to be honest

Actually, I need to record my lectures daily. OPUS 32kbps (mono) does maintain well in both quality and data consuming. In case of high-quality recording, WhatsApp does not allow sending more than 16MB single audio file(s). So, I found this OPUS setup very good in such circumstance. It takes hardly 10MB for a 40-minute lecture/dictation recording. 🙂

> What I mean is that you can try to set 128kbps Opus quality for your recording - does it sound fine then?

128kbps (stereo) in opus is matchless. I have all my music files in OPUS in 128kbps.

Thanks, dear.

**Comment by stsaz** [comment]
> now it is okay

Glad to hear that!  
I can only guess your problem was due to "Dynamic Audio Normalizer: Enabled" setting.

> OPUS 32kbps (mono)

Just in case you didn't know: Opus-VOIP mode (also supported by phiola) should provide even better quality for voice recordings with ultra-low bitrate settings.
