### ISSUE TITLE
Codepage for non-Unicode text

### ISSUE THREAD

**Issue by hsh-ru** [stsaz/phiola#24]
Hello, thanks for the great player.

**fmedia** had the ability to specify the encoding for non-Unicode text in the fmedia.conf:
`# codepage for non-Unicode text: win1251 | win1252`

How to do this in phiola?

In songs where tags are specified in win1251, phiola incorrectly displays song titles:
![cp1251](https://github.com/stsaz/phiola/assets/5989126/2a5089a0-34cb-496c-9163-89b0f1612d3a)

**Comment by stsaz** [comment]
Hi!
Actually, there are several issues here:
1. phiola doesn't have a config file currently.  I initially thought that it won't be needed, but now I start to think that there must be a way to at least specify non-Unicode codepage somewhere...
2. Then I wanted to suggest you using `phiola -Codepage win1251 gui` command-line, but surpisingly it doesn't work either :)

So, clearly there is some work that needs to be done...  Thank you very much for bringing this up!

**Comment by stsaz** [comment]
> phiola -Codepage win1251 gui

Fixed in rc20.  You may use the `-Codepage` switch every time you run phiola.

Or you can add `Codepage win1251` setting into `[phiola app directory]/phiola.conf`:
```sh
echo 'Codepage win1251' >>[phiola app directory]/phiola.conf
```
And the next time you run `phiola gui` it should display the track titles correctly.

**Comment by hsh-ru** [comment]
Thanks, the problem is fixed.
