### ISSUE TITLE
When recording a long audio, split the output into separate smaller files

### ISSUE THREAD

**Issue by davemac327** [stsaz/phiola#26]
Similar to the arecord Linux utility, if the user wants to record a really long audio, allow the user to specify a maximum length per file and have phiola write out multiple files until the entire audio is captured in files. For example, if I want to record 14 hours of audio, and I want each file to be no more than 5 minutes long, I'd specify a maximum file length of 300 seconds, and phiola would write the first 5 minutes to a file ending in -01.wav, then the second 5 minutes to a file ending in -02.wav, and so on until recording is stopped. This could work with the remote option where phiola just keeps writing out files until it gets the remote stop command. Thank you.

**Comment by stsaz** [comment]
Hi!
Since rc22 you can do so, e.g. to split by 5 minutes:
`phiola rec -split 5:0 -o rec-@nowdate-@nowtime.flac`
or
`phiola rec -split 5:0 -o rec-@counter.flac`
