### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Cwpute** [stsaz/phiola#3]
I'm discovering phiola and finding it is very feature-full ! Some of it is quite specific, and having the text localized might help some users discover its features.

I've used external platforms like Weblate (opensource and self-hostable) and Crowdin (free for opentource projects) and they're éoth quite good for that matter.
I would be able able to provide localization for french :)

But maybe this is out of scope for this project ?

**Comment by stsaz** [comment]
Hi!  Yes, good idea!  Although not everything can be localized currently (e.g. CLI help text is hard-compiled into the binary), but we can quite easily localize GUI for desktop OS.

For now there's only one way to do so:
* Translate `lang_en.conf` file to `lang_fr.conf`
* Send me the translated file as PR or attached
English text is here: https://github.com/stsaz/phiola/blob/beta/src/gui/lang_en.conf.  The same file is located in `phiola-2/mod/gui/` directory.

I'll try to read some docs about how to do that on Crowdin...

**Comment by stsaz** [comment]
> or can i do it wn my smartphone somehow ?

No problem, you just need to load the `lang_en.conf` into any text editor and translate, you don't even need to preserve the proper tabulation/spacing as it's just for convenience.  Then just attach your file here and that's all - I'll add it to the project myself.

> do i need android studio

No, you don't need to install anything for this.  However, phiola isn't currently ready for localization on Android - there's still some work needs to be done to make that happen.  Only Linux and Windows GUI support localization right now.

> If it's not possible i'll wait for the project to be up on Crowdin then :)

If that's more convenient for you - I agree, I'll notify you here when I prepare the workspace there.

**Comment by stsaz** [comment]
I registered the project on Weblate and added Android strings there:
https://hosted.weblate.org/projects/phiola/android-strings/
Please take a look.
I don't have enough experience with the platform, but I will try to configure it so it can push changes to Github automatically...

P.S.
I also tried Crowdin but it denied my request to create new project.  Googling showed me that the reason is because I live in Russia.  So this means that phiola and Crowdin can't be friends :)

**Comment by stsaz** [comment]
French strings are added in beta15.

P.S. There are more strings that can be localized now.
