### ISSUE TITLE
CLI recording slow start on Linux x86

### ISSUE THREAD

**Issue by denglerchr** [stsaz/phiola#34]
Hello, I found that recording 2 seconds of audio on Linux takes around 4 seconds in total. Checked on 2 different PCs just to be sure.

`time ./phiola record -o test.wav -until 2 `
gives me
```
φphiola v2.0.24 (linux-amd64)
15:47:57.360 #3617 INFO   tui: *1: Recording...  Source: int16 44100Hz stereo.  Press "s" to stop.
0:01  [..........] -40dB / -19.40dB  
15:47:59.359 #3617 INFO   wav-write: *1: total samples: 88,200
15:47:59.360 #3617 INFO   file-write: *1: test.wav: written 345KB
./phiola record -o test.wav -until 2  0.01s user 0.01s system 0% cpu 4.016 total
```

Compared with arecord:
`time arecord -t wav -d 2 -r 44100 -f SE_16_LE|> test.wav `
```
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono
arecord -t wav -d 2 -r 44100 -f S16_LE  0.01s user 0.01s system 0% cpu 2.242 total
 > test.wav  0.00s user 0.01s system 0% cpu 2.242 total
```

**Comment by stsaz** [comment]
Hi!
phiola uses PulseAudio by default, and phiola receives the very first audio chunk from PA after almost 2 seconds.
`parecord` program works similar:

```
$ time parecord 1.wav
...
real    0m3.344s

$ phiola i 1.wav 
#1 " - " "1.wav" 0.25MB 0:01.486 (65,536 samples) 1411kbps WAVE int16 44100Hz stereo
```

Therefore, I don't think that I can make PA initialize faster than it does.  I can only suggest you ask PA maintainers about why is that so.

> Compared with arecord

You should compare it with phiola recoding via ALSA (and not PA):

```
$ time phiola rec -o 1.wav -u 2 -au alsa
...
real    0m2.276s
```

**Comment by denglerchr** [comment]
Ok thanks for the clarification, weird that pulseaudio starts so slowly, but then it is not on phiola side it seems
