### ISSUE TITLE
[FAEATURE REQUEST] Volume in CLI

### ISSUE THREAD

**Issue by Ducke1001** [stsaz/phiola#35]
I can't find a volume setting in the CLI commands. It is present in the GUI.
Have I overlooked something or is it not implemented there?

**Comment by stsaz** [comment]
While playing audio, the keys to change the volume in TUI are `Up Arrow` and `Down Arrow`.

**Comment by Ducke1001** [comment]
Ok. But it would be nice to be able to set a starting value. If I'm working, for example, I could start with 25% volume. Or can I set the start value in the config?

**Comment by Ducke1001** [comment]
I thought again. You use the system volume as a basis, OK.
What would be important for me is to prevent sound output during a recording without generally blocking the sound in the system. Is that possible?

**Comment by stsaz** [comment]
Can you elaborate on your use-case?  What kind of sound output do you want to prevent while recording?

**Comment by Ducke1001** [comment]
Yes you are right. I need to describe it better.
At the moment I'm using Streamripper from Github to record from web radio. I can record one station with Streamripper and listen to another station with another program. However, Streamripper is very old and cannot convert for example aac files to mp3.
I would like to replace the Streamripper with Phiola.

**Comment by stsaz** [comment]
Added `-vol` option in v2.1-beta3.
Use `-volume 0` to initially mute the audio.

**Comment by Ducke1001** [comment]
Thanks, it works fine. It only cracks once at the start of the recording.
