### ISSUE TITLE
phiola.exe (also phiola-gui.exe) crash  while playing m3u file with radio stations when going next / previous

### ISSUE THREAD

**Issue by 0hip** [stsaz/phiola#36]
Happens with all version up to latest phiola-2.1-beta2

ONLY while playing m3u file with online radio stations:
 Pressing key 'n' for next track or 'p' for previous one goes OK if I don't do it too fast (more than 1 second between presses)

Runs fine with local files.

[phiola-crashdump-6648d725.txt](https://github.com/stsaz/phiola/files/15366109/phiola-crashdump-6648d725.txt)
[cmd_output.txt](https://github.com/stsaz/phiola/files/15366110/cmd_output.txt)
[RADIOS.m3u.txt](https://github.com/stsaz/phiola/files/15366114/RADIOS.m3u.txt)

**Comment by stsaz** [comment]
Easily reproducable on Linux, thank you for the info!

**Comment by stsaz** [comment]
Fixed in v2.1-beta3
