### ISSUE TITLE
Arguments -aformat/-rate/-channels are not work

### ISSUE THREAD

**Issue by colinz2** [stsaz/phiola#39]
### Version
phiola-2.0.24-windows-x64

### Test
```
 ./phiola record -loopback -aformat int16 -rate 16000 -channels 1 -o audio.wav
φphiola v2.0.24 (windows-amd64)
08:33:14.365 #39344 INFO   tui: *1: Recording...  Source: float32 48000Hz stereo.  Press "s" to stop.
0:03  [..........] -40dB / -40dB
08:33:17.984 #39344 INFO   wav-write: *1: total samples: 172,320
08:33:18.002 #39344 INFO   file-write: *1: audio.wav: written 1347KB
```
Open the recorded wav audio with foobar2000, the sample rate and aformat are not right

![image](https://github.com/stsaz/phiola/assets/6488835/e74411c5-060c-45ed-bba7-1e3fbc9cd3a4)

**Comment by colinz2** [comment]
seems the resample process is not taking effect

**Comment by stsaz** [comment]
> seems the resample process is not taking effect

Yes, it seems that way.  I'll check and fix that.  For now, you can use this chained command:

```
phiola record -loopback -o @stdout.wav | phiola convert @stdin -aformat int16 -rate 16000 -channels 1 -o audio.wav
```

**Comment by stsaz** [comment]
> phiola record -loopback -aformat int16 -rate 16000 -channels 1 -o audio.wav

It should work in v2.1-rc4, please check.

**Comment by colinz2** [comment]
It works , thanks
