### ISSUE TITLE
Accesing a playlist that is not empty crashes app

### ISSUE THREAD

**Issue by Cwpute** [stsaz/phiola#4]
Phiola crashes when i put folders, files or anything in any playlist and tap on the Playlist tab to access it.

Phiola v2-beta11
Android11
Nokia Ta-1157

**Comment by stsaz** [comment]
Looks like either phiola on Android11 doesn't work for some reason, or the CPU doesn't support some instruction phiola's code is trying to call...  Need to debug.

If you could reproduce this with your phone cable-connected to PC and collect logs, this will be of huge help.  Here's how to do that:
* Download and unpack Google Android platform tools (the package is very small, e.g. for Linux it's just 6MB)
* Connect your phone to PC
* Run the log collecting process `.../platform-tools/adb logcat >phiola-android.log`.
* Reproduce the issue.  Now there must be a block of lines inside the log file starting and ending with `***` - this is what I'm interested in (for more details see https://developer.android.com/games/optimize/crash#reading-stack-traces)
* Send me the log file by email or attach here (in any case ensure that none of your private info leaks, who knows what other apps on your phone may print!!!)

Unfortunately, I can't automate this process right now.

**Comment by stsaz** [comment]
Here's the update that may resolve this issue:
https://github.com/stsaz/phiola/issues/6#issuecomment-1868225060

Please try the new APK `beta12a` from the link above.

**Comment by stsaz** [comment]
@Cwpute 
beta13 should work, please check.

**Comment by Cwpute** [comment]
> Here's the update that may resolve this issue: [#6 (comment)](https://github.com/stsaz/phiola/issues/6#issuecomment-1868225060)
> 
> Please try the new APK `beta12a` from the link above.

Hey ! sorry for not having contacted you before. I tested `beta12a` yesterday, and the problem is solved on my side :) i thought i had sent an answer through mail already
