### ISSUE TITLE
[Android 11, v2.1-rc4] Recorded files are not added to playlist

### ISSUE THREAD

**Issue by elishamint** [stsaz/phiola#41]
After doing a recording, the playlist is not updated accordingly. No files are dispayed.
Recording works, albeit not respecting the quality setting (see other issue I'll file). My recording file path contains a space character which is handled correctly.

The playlist file that is generated, <user>/phiola/list1.m3uz looks like this:

```
(µ/ý =é#EXTM3U
#EXTINF:-1,  
/storage/emulated/0/phiola/list1.m3uz
```

(which is not a valid EXTM3U file so I don't recognise the binary bit at the beginning)

On program restart the file `list1.m3uz` *may or may not* show up. I tried to edit the list file manually to add an actual recording (including the full file path, see below) and make it a valid EXTM3U file. That did work in a way: after program start, the list still shows `list1.m3uz` as the only entry yet when tapping on that file name the two files which I had manually edited in show up and can also be played. Yet, on program close, the list file is either being modified in either one of these ways (notably not always the same): changed `#EXTINF` value (to 8) all else left as is; reverted to its initial state; being binaryfied (compressed?).

Example edit of `list1.m3uz` that did work:

```
#EXTM3U
#EXTINF:8,  
/storage/emulated/0/Music/Sound records/rec_20240617_102638.m4a
#EXTINF:8,  
/storage/emulated/0/Music/Sound records/rec_20240617_102727.m4a
```

**Comment by stsaz** [comment]
> After doing a recording, the playlist is not updated accordingly.

Yes, and phiola is not supposed to do that by default.  I think I can add an option for that.

> The playlist file that is generated, /phiola/list1.m3uz

`m3uz` is a m3u file compressed with zstd, that's why it's binary.

**Comment by stsaz** [comment]
> After doing a recording, the playlist is not updated accordingly.

Added a new setting for this in v2.2-beta1 (turned off by default).
