### ISSUE TITLE
[Android 11, v2.1-rc4] Recording compression setting is not respected

### ISSUE THREAD

**Issue by elishamint** [stsaz/phiola#42]
Set the bitrate to 192 kbps with AAC-HE compression, it still records with only 128 kbps.

(Btw. there is no WAV format option shown with my device yet FLAC is available so that's a minor issue for the time being.)

**Comment by stsaz** [comment]
> Set the bitrate to 192 kbps with AAC-HE compression, it still records with only 128 kbps.

This is how FDK AAC encoder works.  I guess that you don't want to use HE for such large bitrate values - just use LC instead.

> there is no WAV format option

It's not included because FLAC is better option for lossless recording.  Recording to uncompressed WAV wears out phone's storage device.
