### ISSUE TITLE
Read aac info

### ISSUE THREAD

**Issue by Ducke1001** [stsaz/phiola#44]
I want to read the file info of all aac files in a folder (actually all supported files). This is not a problem with mp3, but with aac phiola reads the whole file in fast forward. It then stops shortly before the end.

>D:\Programmierung\wxbasic\Projects\dsmPlayer\Records>D:\Programmierung\wxbasic\Projects\dsmPlayer\ThirdParty\phiola-2\phiola info -tags -inc "*.aac" .
φphiola v2.1.5 (windows-amd64)
#1 " - " "./OGLAK - About.aac" 2.43MB 3:36.775 (9,559,813 samples) 0kbps HE-AAC int16 44100Hz stereo
[==============================================================..] 3:32 / 3:36

When I read the stream I get one line for every second. This slows down reading immensely.
Actually, I only need the title length.

**Comment by stsaz** [comment]
Fixed in v2.2-beta3.
Note that some decoding is still required to determine the AAC stream type (HE or LC) but a lot less than previously.
The best way to improve this even further is to parse the stream by my own code, but currently I have not enough knowledge on the subject.

**Comment by Ducke1001** [comment]
Now it works fine. Thank you.
