### ISSUE TITLE
CUI option --volume

### ISSUE THREAD

**Issue by superuser7777** [stsaz/phiola#45]
I am an fmedia user.
We welcome the development of phiola!

I think the fmedia options are being implemented one after another, but I'm especially looking forward to the implementation of the '--volume' option.

**Comment by stsaz** [comment]
Hi!
There is an option that lets you set the default volume for playback:

```
phiola play -h
...
  -volume NUMBER        Set initial volume level: 0..100
```

**Comment by superuser7777** [comment]
Sorry, I overlooked it!
thank you!
