### ISSUE TITLE
Recursive Search

### ISSUE THREAD

**Issue by Ducke1001** [stsaz/phiola#46]
If I want to get the file info of all files in a certain directory, then all files from the subdirectories are also listed. How can I prevent this?
I only need the main directory.

Command:
`phiola.exe" info "D:\MP3\Chill Out" -inc "*.mp3"`

**Comment by stsaz** [comment]
In this case you should pass to phiola a wildcard, e.g.
```
phiola.exe info "D:\MP3\Chill Out\*.mp3"
```

**Comment by Ducke1001** [comment]
Yes, it works. Thank you.

How can I do this with all supported formats?

`phiola.exe info "D:\MP3\Chill Out\*.*"`

reads the subdirectories again. Using the Phiolas Format Detector I was able to filter out the unsupported formats.
Do I have to go the long way and insert the path for all formats individually, e.g.

`phiola.exe info "D:\MP3\Chill Out\*.mp3" "D:\MP3\Chill Out\*.aac" "D:\MP3\Chill Out\*.ogg" ...` ?

**Comment by stsaz** [comment]
> `phiola.exe info "D:\MP3\Chill Out\*.*"`
> reads the subdirectories again

If a directory contains a dot then yes, it will be included in the search.
To work-around that you can try using `*.??`, `*.???` and `*.????` masks, or explicitly specifying all supported file types as you already tried.

Note that on Linux there is no such problem, because one would just use `find ... | xargs phiola info` command for your scenario.

**Comment by Ducke1001** [comment]
Thanks for your advice. I will try it.
I would also prefer to work in Linux but I can't install wxBasic under Linux Mint. It wants libraries that I can't find anywhere.

**Comment by stsaz** [comment]
One of the main advantages of Linux is that the libs are open-source, and thus you can always build them manually if necessary.  But if you're stuck, send me an email directly - I will try to help you.
