### ISSUE TITLE
Some tracks are missing when splitting FLAC files.

### ISSUE THREAD

**Issue by HongYue1** [stsaz/phiola#47]
Splitting a CUE for that two FLAC files ignores the first track of the second file. in my case Track no 4 "Тысяча Сто".

Cue file:
```
REM GENRE "Heavy Metal"
REM DATE 1987
REM COMMENT С60 27413 000
PERFORMER "Ария"
TITLE "Герой Асфальта"
FILE "Ария - Герой Асфальта Side A.flac" FLAC
  TRACK 01 AUDIO
    TITLE "На Службе Силы Зла"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Герой Асфальта"
    INDEX 01 07:12:12
  TRACK 03 AUDIO
    TITLE "Мёртвая Зона"
    INDEX 01 12:24:48
FILE "Ария - Герой Асфальта Side B.flac" FLAC
  TRACK 04 AUDIO
    TITLE "Тысяча Сто"
    INDEX 01 00:00:00
  TRACK 05 AUDIO
    TITLE "Улица Роз"
    INDEX 01 04:55:05
  TRACK 06 AUDIO
    TITLE "Баллада О Древнерусском Воине"
    INDEX 01 10:51:29
```

CLI output: 
```
φphiola v2.2-rc4 (linux-amd64)

#2 "Ария - Герой Асфальта" "/content/(Heavy Metal) [LP] [24_192] Ария - Герой Асфальта - 1987, FLAC (image .cue)/Ария - Герой Асфальта Side A.flac" 743.05MB 5:12.000 (59,904,000 samples) 5450kbps FLAC int24 192000Hz stereo

[===================.............................................] 2:09 / 7:1213:14:20.923 #6448 ERROR  dbus-sleep: ffps_systimer()
[=============================================...................] 5:06 / 7:12
13:14:29.548 #6451 INFO   file-write: *3: 02 Герой Асфальта.flac: written 198768KB

#3 "Ария - Мёртвая Зона" "/content/(Heavy Metal) [LP] [24_192] Ария - Герой Асфальта - 1987, FLAC (image .cue)/Ария - Герой Асфальта Side B.flac" 756.48MB 4:55.000 (56,640,000 samples) 5483kbps FLAC int24 192000Hz stereo

[==========================......................................] 2:04 / 4:55
13:14:34.397 #6448 INFO   file-write: *2: 01 На Службе Силы Зла.flac: written 275458KB
[===============================================================.] 4:54 / 4:55
13:14:39.418 #6451 INFO   file-write: *4: 03 Мёртвая Зона.flac: written 190669KB

#4 "Ария - Улица Роз" "/content/(Heavy Metal) [LP] [24_192] Ария - Герой Асфальта - 1987, FLAC (image .cue)/Ария - Герой Асфальта Side B.flac" 756.48MB 5:56.000 (68,352,000 samples) 5483kbps FLAC int24 192000Hz stereo

[................................................................] 0:04 / 5:5613:14:39.518 #6448 ERROR  dbus-sleep: ffps_systimer()
[===============================================================.] 5:55 / 5:56
13:14:47.499 #6451 INFO   file-write: *5: 05 Улица Роз.flac: written 231211KB

#5 "Ария - Баллада О Древнерусском Воине" "/content/(Heavy Metal) [LP] [24_192] Ария - Герой Асфальта - 1987, FLAC (image .cue)/Ария - Герой Асфальта Side B.flac" 756.48MB 8:25.923 (97,137,305 samples) 5483kbps FLAC int24 192000Hz stereo

[=====================...........................................] 2:52 / 8:2513:14:52.418 #6448 ERROR  dbus-sleep: ffps_systimer()
[................................................................] 0:00 / 8:25
13:15:00.182 #6451 INFO   file-write: *6: 06 Баллада О Древнерусском Воине.flac: written 329665KB
```

![image](https://github.com/user-attachments/assets/6ed01f96-707a-4ac5-9588-e26dfeab96a3)

**Comment by HongYue1** [comment]
> Hi! Multiple FILE entries in a single .cue file just don't work currently - it's the first time I see such scenario. This will be addressed in the upcoming version.
> 
> > TITLE "Герой Асфальта"
> 
> It's funny, because I just recently was listening to this album :)

Great, Thanks!
Nice taste in Music by the way.

**Comment by HongYue1** [comment]
by the way, is it possible to add a flag which automatically convert the CUE file to UTF-8 before read it? I think it's way easier than having to specify the type of the unicode of the file, especially when dealing with batch conversion.

**Comment by stsaz** [comment]
> is it possible to add a flag which automatically convert the CUE file to UTF-8 before read it?

phiola must not modify the input files in any way - I'd consider this as bad behavior otherwise.
Surely, I can add a separate command to convert text files, but phiola is not supposed to be a text editor - proper text utilities will be much much better at this anyway.

There are several possible solutions for your use-case:

* use `-codepage ...` CLI option each time
* set `Codepage ...` option in `phiola.conf` file once and for all
* use Linux utils to convert the files (see https://stackoverflow.com/questions/64860/best-way-to-convert-text-files-between-character-sets)

Note that there are only a few codepage values supported by phiola at this time: `win866`, `win1251` and `win1252`, so the third option is the best.

**Comment by HongYue1** [comment]
> > is it possible to add a flag which automatically convert the CUE file to UTF-8 before read it?
> 
> phiola must not modify the input files in any way - I'd consider this as bad behavior otherwise. Surely, I can add a separate command to convert text files, but phiola is not supposed to be a text editor - proper text utilities will be much much better at this anyway.
> 
> There are several possible solutions for your use-case:
> 
> * use `-codepage ...` CLI option each time
> * set `Codepage ...` option in `phiola.conf` file once and for all
> * use Linux utils to convert the files (see [stackoverflow.com/questions/64860/best-way-to-convert-text-files-between-character-sets](https://stackoverflow.com/questions/64860/best-way-to-convert-text-files-between-character-sets))
> 
> Note that there are only a few codepage values supported by phiola at this time: `win866`, `win1251` and `win1252`, so the third option is the best.

I will stick with the third option then, thanks!

**Comment by stsaz** [comment]
Should work in v2.2.5, please verify.

**Comment by HongYue1** [comment]
> Should work in v2.2.5, please verify.

I have just tested it and it works fine now, Thank you!

![image](https://github.com/user-attachments/assets/f02b1aac-0c6d-4b4f-94a9-f152d33fc22a)
