### ISSUE TITLE
Phiola v2.2.5 (windows-amd64) Crash when playing this OPUS stream. Both CLI and GUI

### ISSUE THREAD

**Issue by 0hip** [stsaz/phiola#49]
Crash with this radio station with OPUS stream
http://proteusradio.ddns.net:9900/proteus.opus

[Debug.txt](https://github.com/user-attachments/files/17015996/Debug.txt)
[phiola-crashdump-66e85527.txt](https://github.com/user-attachments/files/17015998/phiola-crashdump-66e85527.txt)

Plays fine with this one:
http://radio.glafir.ru:7000/easy-listen/va-romantic-piano-moments-to-remember

**Comment by stsaz** [comment]
Hi!  I've released v2.2.6 that should no longer crash, but there is a problem with your second radio link (unsupported case when the server starts a new track) - I will update on this later.

**Comment by 0hip** [comment]
Indeed no longer crashes with v2.2.6 release!

**Comment by stsaz** [comment]
With phiola v2.2.7 your second link should work fine.  The problem was that chained OGG streams were not supported.  Thank you for notifying me on the issues!
