### ISSUE TITLE
Record button doesn't do anything

### ISSUE THREAD

**Issue by Cwpute** [stsaz/phiola#5]
The record button seemingly doesn't do anything for me. If i try to push it nothing happens, i don't get a toast message or any feedback saying anything happened. Is anything happening ?
I did give the mic permissions to the app earlier.

Phiola v2-beta11
Android11
Nokia Ta-1157

**Comment by stsaz** [comment]
fixed in beta12:
```
- Android: recording didn't work until config file is first written
```
