### ISSUE TITLE
Connect to web radio

### ISSUE THREAD

**Issue by Ducke1001** [stsaz/phiola#51]
I have many stations that I cannot hear with phiola. Here is a small list with the corresponding error message:

`D:\Programmierung\wxbasic\Projects\dsmPlayer\ThirdParty\phiola-2>phiola http://timesradio.wireless.radio/stream?ref=rf
 #57988 ERROR  dir open: http://timesradio.wireless.radio: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch

phiola "http://timesradio.wireless.radio/stream?ref=rf"
 #31980 ERROR  dir open: http://timesradio.wireless.radio: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch

phiola "http://176.9.86.211:8023/stream
φphiola v2.2.7 (windows-amd64)

phiola "http://streaming.radionomy.com/JamendoLounge?lang=en-US%2cen%3bq%3d0.5"
 #56056 ERROR  dir open: http://streaming.radionomy.com: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch

phiola "http://159.69.217.78:8000/?radio=radio2000.mp3"
 #37804 ERROR  dir open: http://159.69.217.78:8000: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch

phiola "http://schlager.stream.laut.fm/schlager?pl=m3u&t302=2018-07-27_15-18-07&uuid=4c44a06e-f324-4ca3-8fa5-75e8dfe968a4"
 #63308 ERROR  dir open: http://schlager.stream.laut.fm: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch

phiola "http://nrj.de/muenchen"
φphiola v2.2.7 (windows-amd64)
18:57:28.465 #59048 ERROR  http-client: *1: auto-switching to secure HTTP isn't supported yet

phiola-2>phiola "https://player.ffn.de/radioffn.mp3"
φphiola v2.2.7 (windows-amd64)
18:58:47.790 #51268 ERROR  http-client: *1: auto-switching to plain HTTP isn't supported yet

phiola "http://campusfm.de"
φphiola v2.2.7 (windows-amd64)
18:59:33.268 #41440 ERROR  http-client: resource unavailable: 400 Bad Request

phiola "http://www.antenne.de/webradio/channels/80er-kulthits.m3u"
φphiola v2.2.7 (windows-amd64)
19:01:10.661 #48788 ERROR  http-client: *1: auto-switching to secure HTTP isn't supported yet

phiola "http://185.33.21.111/costadelmarchillout_128"
φphiola v2.2.7 (windows-amd64)
19:02:32.001 #57072 WARN   http-client: *1: connect to 185.33.21.111 (185.33.21.111:80): (121) Das Zeitlimit für die Semaphore wurde erreicht
19:02:32.002 #57072 ERROR  http-client: *1: no next address to connect`

"resource unavailable" probably means that the address does not exist. In contrast, "Das Zeitlimit für die Semaphore wurde erreicht" probably means that the address does exist, but no connection could be established.

Can you take a look at the other addresses or error messages and fix the errors or ensure support?

**Comment by stsaz** [comment]
Hi!
Several issues here:

1. (Windows) URLs with `?` character do not work because phiola thinks it's a local path wildcard.

	```
	phiola http://timesradio.wireless.radio/stream?ref=rf
	#57988 ERROR dir open: http://timesradio.wireless.radio: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch
	```

2. URLs with query strings are not passed to server.

3. phiola can't redirect between http and https URLs.  Known issue.

	> ERROR http-client: *1: auto-switching to secure HTTP isn't supported yet


4. Can you check if any other player plays this stream?  Maybe the server expects some additional HTTP request headers...

	```
	phiola "http://campusfm.de"
	φphiola v2.2.7 (windows-amd64)
	18:59:33.268 #41440 ERROR http-client: resource unavailable: 400 Bad Request
	```

5. This is pure network error.

	> WARN http-client: *1: connect to 185.33.21.111 (185.33.21.111:80): (121) Das Zeitlimit für die Semaphore wurde erreicht


So the issues 1 & 2 are easy to fix; issue 3 may take some time.
Issue 4 - if you can make another player work with this URL - please post some details, I'll look into it.

**Comment by Ducke1001** [comment]
Issue 4: The Windows Media Player and Vlc doesn't play it either. I think the address no longer exists.

**Comment by Ducke1001** [comment]
Can phiola handle HLS streams? All BBC radio streams have been switched to HLS. For example:

`phiola http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8`

does not give me any message back.
This stream works in VLC.

**Comment by Ducke1001** [comment]
That sounds good. It would be great if you could do that.

**Comment by stsaz** [comment]
Issues 1 and 2 are resolved in v2.2.8.
The only issue left is no.3, but it's not easy to implement.
Also, HLS support is still not ready.

**Comment by Ducke1001** [comment]
Thanks for the correction and for continuing to work on it. I believe you that it is not easy and takes time.

**Comment by stsaz** [comment]
@Ducke1001 
I added HLS playback in v2.3-beta0.
Your BBC radio link didn't work for me at all (I guess there's a network problem), but I found some other link, which streams in ts(AAC) format, and it works for me.
Anyway, can you test several more HLS streams and if you'll find any problems - just post them here?

**Comment by Ducke1001** [comment]
Thank you very much.
Strange, the BBC link still works with VLC.
I will test different HLS stream addresses and let you know if it worked.

**Comment by Ducke1001** [comment]
Ok, here are some test results:
[https://stream.bodkas.com/playlist?id=chadafmradio](url)
09:47:18.787 #5012 ERROR  format-detector: *1: https://stream.bodkas.com/playlist?id=chadafmradio: file format not supported

[https://a.files.bbci.co.uk/ms6/live/3441A116-B12E-4D2F-ACA8-C1984642FA4B/audio/simulcast/hls/nonuk/audio_syndication_low_sbr_v1/aks/bbc_radio_fourfm.m3u8](url)
works

The stream from above
[http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8](url)
works, as well as all the others I have tested from BBC, 

[https://partwota.cdn.mgmlcdn.com/shababrdoorg/shababrdo.stream_aac/master.m3u8](url)
10:00:34.197 #8532 ERROR  http-client: *1: no more files in m3u

[https://sdn-global-live-streaming-packager-cache.3qsdn.com/64733/64733_264_live.m3u8](url)
10:08:10.116 #2868 ERROR  http-client: *1: no more files in m3u
phiola hangs

**Comment by Ducke1001** [comment]
Oh, here is a crash with this link:
[https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3](url)

> phiola "https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3"
φphiola v2.3-beta0 (windows-amd64)
phiola crashed: ...\Dirk\AppData\Local\Temp\phiola-crashdump-6738f462.txt
phiola  "https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3"
phiola v2.3-beta0 (windows-amd64)
Signal:3221225477  Address:0x00000000000000f0  Flags:0  Thread:11460
#0: 0x00007ff6277eaf1d  \phiola.exe+0xaf1d
#1: 0x00007ff6277e2123  \phiola.exe+0x2123
#2: 0x00007ffb8b9ab21c  \KERNELBASE.dll+0x16b21c
#3: 0x00007ffb8df797fd  \ntdll.dll+0xa97fd
#4: 0x00007ffb8df5f687  \ntdll.dll+0x8f687
#5: 0x00007ffb8df7517f  \ntdll.dll+0xa517f
#6: 0x00007ffb8deee856  \ntdll.dll+0x1e856
#7: 0x00007ffb8df7416e  \ntdll.dll+0xa416e
#8: 0x00007ffb85c0ebc7  \http.dll+0xebc7
#9: 0x00007ffb85c07a0e  \http.dll+0x7a0e
#10: 0x00007ffb877b6b0d  \libphiola.dll+0x6b0d
#11: 0x00007ff6277f41ea  \phiola.exe+0x141ea
#12: 0x00007ff6277e13ae  \phiola.exe+0x13ae
#13: 0x00007ff6277e14e6  \phiola.exe+0x14e6
#14: 0x00007ffb8cc8257d  \KERNEL32.DLL+0x1257d
#15: 0x00007ffb8df2af08  \ntdll.dll+0x5af08

[phiola-crashdump-6738f462.txt](https://github.com/user-attachments/files/17787748/phiola-crashdump-6738f462.txt)

**Comment by Ducke1001** [comment]
It seems like it's a new problem. I'm having this issue now with many channels that didn't have an issue before.

**Comment by stsaz** [comment]
Hi!
v2.3-beta1 should work for all cases except:

> ...64733_264_live.m3u8

It looks like an audio+video stream -- I'm not sure it's a good idea to use phiola for that.

And the issue

> ERROR http-client: *1: auto-switching to secure HTTP isn't supported yet

is still to be resolved.

**Comment by Ducke1001** [comment]
Many thanks.

>It looks like an audio+video stream -- I'm not sure it's a good idea to use phiola for that.

Ah, I didn't know that. If anyone thinks this is an audio stream and tries to open it, phiola hangs.
Can you prevent this?

>phiola "https://partwota.cdn.mgmlcdn.com/shababrdoorg/shababrdo.stream_aac/master.m3u8" -connect_timeout 15 -recv_timeout 15

gives me the error 
>18:14:01.246 #5332 ERROR  http-client: *1: bad UTF-8 URL

Why is that?

**Comment by Ducke1001** [comment]
I more often get the error message
> 07:51:51.351 #10376 ERROR  http-client: *2: host resolve: stream.bigfm.de: Dies ist normalerweise ein zeitweiliger Fehler bei der AuflÃ¶sung von Hostnamen. Grund ist, dass der lokale Server keine RÃ¼ckmeldung vom autorisierenden Server erhalten hat

and phiola ends. The next time you call up the address it works.
Can phiola try to reconnect on her own until the timeout set is over?

**Comment by stsaz** [comment]
> auto-switching to secure HTTP isn't supported yet

Should work in v2.3-beta2

> If anyone thinks this is an audio stream and tries to open it, phiola hangs.

v2.3-beta2 should report an error in this case.  Please verify.

> bad UTF-8 URL

The server returns the content compressed with gzip sometimes -- and this seems like an incorrect behaviour from server (phiola doesn't support gzip nor it informs the server that it should compress the data).  I really don't want to add gzip support unless absolutely necessary, and 1 misbehaving server is not convincing enough...

> ERROR http-client: *2: host resolve

Can you attach debug logs so I can better understand what's happening there?  I'm interested if the system DNS resolver  returns an error immediately or after some time.

**Comment by Ducke1001** [comment]
Thank you for everything.
The auto-switching works fine.

> v2.3-beta2 should report an error in this case. Please verify.

Yes, the error message works. There are no more hangs.

> I really don't want to add gzip support unless absolutely necessary, and 1 misbehaving server is not convincing enough...

I can understand that. This really shouldn't happen too often.

> Can you attach debug logs so I can better understand what's happening there? I'm interested if the system DNS resolver returns an error immediately or after some time.

Strange but good, I don't have this problem anymore in the current version.
If it happens again, I'll try using debug logs.
