### ISSUE TITLE
Batch Converter does nothing?

### ISSUE THREAD

**Issue by Radoom** [stsaz/phiola#53]
Hi. Probably me not understanding this tool, but...
How is batch convert supposed to work on Android? 
Running v2.2.7
Want to convert m4a to mp3.

Basic stuff: should the play controls start to play a m4a file either in explorer or playlist1 view?  For me not even that works, nothing happens.

Selecting a native mp3 file works, playback starts fine. So something about m4a files as source? 

For conversion, same. If I have mp3 and convert to m4a this works. 
But vice versa nothing happens when starting the conversion.
Steps: 
1. In explore view I tap every m4a file in a folder one by one to add them to playlist1 view. (Where is "add all" by the way?)
2. In playlist1 view I select "List:convert..." from the menu.
3. I select mp3 as output. At the bottom there is a Switch for stream copy on or off. No matter how I set this....
.... After starting convert no files get created, there is no progress / activity indicator, nothing. Only thing is that tapping on the playlist1 button toggles this to "conversion" and back. 

When I select "file:convert" from the menu it tells me a conversion is already running, so I selected "do nothing" . If I select "interrupt" it says "conversion interrupted" or something like that as a pop-up, but seems to keep running, because if I then select "file:convert" again I get the same pop-up. Loop...

Something wrong in the app for m4a as source format, or do I have broken m4a files ? They play fine in VLC for example if I select them there.

**Comment by stsaz** [comment]
Hi!

> Want to convert m4a to mp3.

Actually, the encoding to MP3 is disabled in phiola, only copying audio from MP3 to MP3 is currently supported.
AAC, Opus and Vorbis are better codecs, do you really need MP3?

It looks like the error reporting in this case is bad -- I should improve that.


> Where is "add all" by the way?

You could try long pressing on the directory you want to add to the playlist.
Alas, interacting with multiple files is a weak spot in phiola UI.


> if I then select "file:convert" again I get the same pop-up.

In this case you should close the existing Conversion list first with `List: Close` command -- this is a safety measure to ensure that the conversion queue is not updated if it already exists.

**Comment by Radoom** [comment]
Hi!
Thanks for your quick response! 
Adding folder by long-press: ok, noted. Unexpected :-)

Tried with target format ogg(vorbis) now. Starting the conversion again seems to do nothing. Toast comes up, says it has been started, but there seems to be nothing going on.
If I then (in the "conversion" view) select List:close it says I should wait until conversion finishes. 
If I select List:clear, same.
If I select List:convertAll, it says again that conversion is already running. 
Stuck in a loop :-)

**Comment by stsaz** [comment]
> If I then (in the "conversion" view) select List:close it says I should wait until conversion finishes.

Then it's likely that the conversion is in progress already.
When files are being converted, phiola shows `[CON]` status at the top, and also the progress for each converted file is updated (e.g. `Track Title [0:00/5:25]`).
If it's not, please show either a screenshot or a text of what your screen looks like -- I am still not sure I understand what's happening.

**Comment by Radoom** [comment]
It shows [CON] at the top, yes, but no progress per song. Screenshots won't tell you anything more I'm afraid. Any logging I can turn on somewhere?

**Comment by stsaz** [comment]
So the first track in Conversion list is stuck at `[0:00/...]` progress? This is quite strange...

OK, I've added debug logging to v2.2.8 -- enable it in About screen by activating the button `Enable debug logging`.
Then reproduce the issue.

* You can save the system logs to a file on your phone by pressing the button `Save system logs to file` in About screen.
* Or you can see the phone's logs on your PC with Google's `adb` utility (with `adb logcat` command)

Then filter the lines by `phiola` keyword and post the latest messages here.
