### ISSUE TITLE
phiola for Windows XP

### ISSUE THREAD

**Issue by antyvir** [stsaz/phiola#54]
Greetings everyone! 
Thanks to the author of the project for this program. Found a note here: Although not officially supported, phiola should build fine for macOS, FreeBSD and Windows XP after tweaking the build script. What script is needed and in general what programs are needed to compile a project for Windows XP 32 bit?
Perhaps someone has already tried to build a project from their provided sources and there are some options. I would be very grateful for any advice.

**Comment by stsaz** [comment]
Hi!  It depends on how you want to build it:
* on old Windows XP machine
* on modern Windows machine
* on modern Linux machine

In case 1 the first step you'll need is to somehow install GCC toolchain.

In other cases the build process should be straightforward inside a Linux container -- I can give you a starting-point script:
https://github.com/stsaz/phiola/blob/build-win32/xbuild-win32.sh
that you should run under Linux (or WSL).

**Comment by antyvir** [comment]
Hi! I installed Debian 11 i386 on Oracle VM VirtualBox. I prepared the directories and downloaded the sources as indicated in the BUILDING.MD file. I downloaded the xbuild-win32.sh script to the phiola directory. After launching and waiting for two hours for the script to work, I get: make: Leaving director
![VirtualBox_Debian11_i386_01_12_2024_18_41_18](https://github.com/user-attachments/assets/baedf752-49d4-40eb-a54f-792898076753)
y '/src/ffpack/_windows-ia32'. This is shown in the attached picture. The compiled phiola-2 directory does not appear in the phiola-src directory. What is my mistake?

**Comment by stsaz** [comment]
> How is it possible to fix it?

Honestly - no idea :)  Looks like it needs to be manually debugged step by step...

---

Anyway, I was able to build phiola for x86:
https://github.com/stsaz/phiola/releases/download/v2.3-beta2/phiola-2.3-beta2-windows-x86.zip

Please check if it works on WinXP.

**Comment by antyvir** [comment]
Hi! 
Thank you very much for taking the time to compile the application. I tested the compiled application on Windows XP Pro SP3. Unfortunately this doesn't work. Attached a screenshot. I think this will not work on WinXP, because the phiola application uses WASAPI for audio output, and in WinXP, by default, Direct-Sound was always used at the software level for audio output. In fact, your application is very cool and cool for modern operating systems.
![WinXP_SP3_phiola](https://github.com/user-attachments/assets/903bf717-bd39-4766-81d7-be095dfaed39)

**Comment by stsaz** [comment]
I added direct-sound module - please redownload the package, then just delete the `phiola-2\mod\wasapi.dll` file from where phiola is unpacked.
When playing files, the error message `wasapi.dll: ffdl_open: Module not found` will show up -- just ignore it.

Please verify that phiola really works now on WinXP.

**Comment by antyvir** [comment]
Hello. Yes, now everything really works as it should. Very grateful! Thank you very much!

**Comment by forcomp2013** [comment]
Hi. A wonderful project, and I would like to thank the author for such a wonderful command line utility. I have a very very old computer with an ancient processor (I think Athlon XP) and Windows XP. On it, phiola-2.3-beta2-windows-x86 does not even start. I read it on the Internet and realized that it’s all about the old processor instructions. Question to the author: is it possible to add compatibility to the program with older processors that only support the entry-level SSE instruction?

**Comment by stsaz** [comment]
@forcomp2013 
Hi!  Yes, most likely some SSE instruction causes your CPU to generate an exception, and phiola crashes.  Can you provide the details on that?  What is printed in the terminal window?  If running `phiola.exe` doesn't even display the help info -- can you run it under MS's `windbg` debugger (https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/) ?  First we need to find the module and instruction that cause the crash.

**Comment by forcomp2013** [comment]
When I go to the folder with the program and type phiola.exe -h on the command line, help on the program’s functions is displayed below. If I type phiola.exe C:\file.mp3, it simply moves to the next line (C:\phiola>) and that’s all. phiola-gui.exe also does not start, I only quickly manage to see the window (frame) flash by. This weekend I will try to run the application under the windbg debugger and report back on the results.

**Comment by stsaz** [comment]
> If I type phiola.exe C:\file.mp3, it simply moves to the next line (C:\phiola>) and that’s all

Please try with debug log:
`phiola -D C:\file.mp3`
and post here the last few lines it prints.

**Comment by forcomp2013** [comment]
Hello. Try with debug log:
phiola -D C:\file.mp3 - it too simply moves to the next line (C:\phiola>) and that’s all. I completely installed Windows XP SP3 with another build. Again on the command line I typed phiola -D C:\file.mp3. I got the errors as in the picture. windbg installed, launched the debugger, selected File -> Export Exutable. Unfortunately, I haven’t worked with a debugger before and don’t have that much experience. If you direct me what else I need to see there, I’m always ready.
![Error_cmd](https://github.com/user-attachments/assets/3f915260-d33c-4d81-bc20-91693f48f99e)
![Error_gui](https://github.com/user-attachments/assets/397f5254-34c3-42b4-9004-b1372c6147ca)
![windbg](https://github.com/user-attachments/assets/b12efe9d-d1d0-48eb-87b2-1524889b7daa)

**Comment by stsaz** [comment]
@forcomp2013 
Thanks for the info!  Indeed, AMD CPUs didn't support SSE2 until Athlon 64 -- I didn't know about that.

Please redownload the 2.3-beta2-x86 package -- I disabled forced SSE2, and now everything should work.

Also, can you test playback of .opus files?  Because I'm currently not sure if the module will detect SSE2 at runtime.

**Comment by forcomp2013** [comment]
Hello! Now everything works as it should. Opus files also play correctly. Thank you for such a useful program! One more question: does this utility normalize the sound level during playback? In the video help there is only the option -danorm "Record and pass the audio through Dynamic Audio Normalizer filter
phiola record". Does this option work when playing regular files?

**Comment by stsaz** [comment]
> Does this option work when playing regular files?

Yes, it does -- type `phiola pl -h` on the info how to use it.
However, keep in mind that it is *dynamic* normalizer -- it's not the same as *replay gain* normalization.
Also, it needs extra CPU power to perform extra work of converting and analyzing audio samples at runtime.
