### ISSUE TITLE
random play

### ISSUE THREAD

**Issue by antyvir** [stsaz/phiola#58]
Greetings! 
Using the program I encountered a problem: on the command line I write phiola play -random C:\Audio\*.* . There are 2 audio files in the Audio folder and the -random option to play a random track. 
This is what happens, but for some reason the tracks are played cyclically. What option should be specified in the initial command to stop endless playing of tracks? I didn't find any option in the help.

**Comment by stsaz** [comment]
Hi!  This is how `-random` switch is designed -- it generates a (pseudo) random number and plays the track, and it never stops, because phiola *can not* know where it should stop.  Perhaps you need a `shuffle` option but it's not implemented in phiola/Windows.
