### ISSUE TITLE
Submenues for burger menu options

### ISSUE THREAD

**Issue by Cwpute** [stsaz/phiola#8]
I see the Android UI is a bit different from that of Linux and Windows, namely, File List Playback Record Convert and Help all have their own submenu.

I guess all Record and Playback options are already visible as i don't see them in the drop-down menu …?
Otherwise, File ande List could have their own menu available like this:
![image2](https://github.com/stsaz/phiola/assets/80604512/572d67be-6496-4cdb-96d3-f2bffb6e759e)
About and Help menues would be available from the tapping the icon on the left, or by tapping the current burger menu if the icon isn't to your liking.

**Comment by stsaz** [comment]
beta14 now has a separate List menu.  I don't think that it's really necessary to make a separate menu for File commands - for now it's better to minimize the number of toolbar buttons. What do you think?

**Comment by Cwpute** [comment]
I don't have a definitive answer to that. I guess we'll have to wait and see what most use cases are, and adapt to that.

On the other hand i don't see why we should minimize the number of buttons ? If it allows one to quickly find the tools they need, i'd say let's do it :) if not then let's not.

Le 30 décembre 2023 07:00:23 GMT+01:00, Simon Zolin ***@***.***> a écrit :

**Comment by stsaz** [comment]
I'll add a separate menu for File commands and see how it looks.  Maybe there will be not enough space for low-res phone screens in the app title with 3 status flags (i.e. `[PLA,STP,REC]`) are set - this requires some testing.

**Comment by Cwpute** [comment]
Didn't know there could be 3 status flags at once.
These status could be communicated through other means though !
* The record button could change color when recording, as well as a notification popping-up if the user changes the foreground app.
* The play button could change color as well vhen a track is playing, same thing with the notification.
* And that would also work with the stop button as well :)
Then the status flags wouldn't be needed anymore, and they wouldn' take tpace elsewhere. What do you think?

Le 11 janvier 2024 05:19:01 GMT+01:00, Simon Zolin ***@***.***> a écrit :

**Comment by stsaz** [comment]
Added separate File menu.
Everything looks fine with 3 status flags and 3 toolbar buttons.

> The record button could change color when recording

Yes, it's colored in red.

> Then the status flags wouldn't be needed anymore

Status flags can be turned off in Settings anyway, so I hope there won't be any issues...

**Comment by Cwpute** [comment]
> > The record button could change color when recording
> 
> Yes, it's colored in red.
Oh my, i knew i was colourblind, but *that* colourblind haha. Didn't see it until you mentioned it !
